[package]
name = "viwo-runtime-luajit"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "LuaJIT runtime for Viwo"

[dependencies]
viwo-ir.workspace = true
mlua.workspace = true
thiserror.workspace = true
serde_json.workspace = true
