[package]
name = "bloom-plugin-abi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Stable ABI for Bloom plugins"

[dependencies]
abi_stable.workspace = true
serde.workspace = true
serde_json.workspace = true
